name: Label Controller

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  label_impact_breaking:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'impact/breaking') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: 'main'
          body-template: |

            ## Breaking changes

            Write your breaking changes here

            ---
          body-update-action: 'suffix'
          body-uppercase-base-match: false

  label_impact_deprecate:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'impact/deprecate') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: 'main'
          body-template: |

            ## Deprecations

            Write your deprecations here

            ---
          body-update-action: 'suffix'
          body-uppercase-base-match: false