name: Pull Request Formatter

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.inputs.pr_number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Format Pull Request
        run: |
          python3 .github/scripts/pr_formatter.py $PR_NUMBER
        env:
          GH_TOKEN: ${{ github.token }}