name: Pull Request Formatter

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  validator:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' && github.event.action == 'edited' && contains(github.event.changes.labels, 'from') }}

    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Format Pull Request
        id: format_pr
        run: "python3 .github/scripts/pr_formatter.py $PR_NUMBER"
        env:
          GH_TOKEN: ${{ github.token }}