name: Pull Request Validator

on:
  pull_request:
    types: edited
    branches:
      - main

jobs:
  validator:
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Check path
        id: validate_pr
        run: |
          ls
          pwd

      - name: Validate Pull Request
        id: validate_pr
        run: "python3 .github/scripts/pr_validator.py $PR_NUMBER"