name: Publish Artifacts to IOTA Environment
on:
  push:
    tags:
      - "*"
  repository_dispatch:
    types: 
      - trigger_publish-artifacts-iota

permissions:
  id-token: write
  contents: read
jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Echo works
        run: |
          echo "Tag name: ${{ github.event.client_payload.tag_name }}"
