name: Publish Artifacts to IOTA Environment
on:
  push:
    tags:
      - "*"
  repository_dispatch:
    types: 
      - trigger_publish-artifacts-iota

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG environment variable
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "TAG=${{ github.event.client_payload.tag_name }}" >> $GITHUB_ENV
          fi

  another_job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use TAG environment variable
        run: echo ${{ env.TAG }}
