name: Publish Artifacts to IOTA Environment
on:
  push:
    tags:
      - "*"
  repository_dispatch:
    types: 
      - trigger_publish-artifacts-iota

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.set_tag.outputs.TAG }}
    steps:
      - name: Set TAG environment variable
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            export TAG="${{ github.ref_name }}"
          elif [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            export TAG="${{ github.event.client_payload.tag_name }}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT

  another_job_0:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use TAG environment variable
        env:
          TAG: ${{ needs.build.outputs.TAG }}
        run: echo $TAG

  another_job:
    runs-on: ubuntu-latest
    needs: another_job_0
    steps:
      - name: Use TAG environment variable
        env:
          TAG: ${{ needs.build.outputs.TAG }}
        run: echo $TAG
